# occupancy grid information
# TODO: check this
world_collision_model:
  size_x: 2.0
  size_y: 2.0
  size_z: 2.0
  origin_x: 0.0
  origin_y: 0.0
  origin_z: 0.0
  res_m: 0.02
  max_distance_m: 2.0

# # TODO: check this
# self_collision_model:
#   frame_id: base_link
#   size_x: 5.0
#   size_y: 5.0
#   size_z: 5.0
#   origin_x: 0.0
#   origin_y: 0.0
#   origin_z: 0.0
#   res_m: 0.02
#   max_distance_m: 0.2

robot_collision_model:
  world_joint:
    name: world_joint  # map(?)
    type: planar  # fixed, floating
  voxels_models:
    - { link_name: base_link, res: 0.01 }
    - { link_name: l_wheel_link, res: 0.01 }
    - { link_name: r_wheel_link, res: 0.01 }
    - { link_name: estop_link, res: 0.01 }
    - { link_name: torso_lift_link, res: 0.01 }
    - { link_name: shoulder_pan_link, res: 0.01 }
    - { link_name: shoulder_lift_link, res: 0.01 }
    - { link_name: upperarm_roll_link, res: 0.01 }
    - { link_name: elbow_flex_link, res: 0.01 }
    - { link_name: forearm_roll_link, res: 0.01 }
    - { link_name: wrist_flex_link, res: 0.01 }
    - { link_name: wrist_roll_link, res: 0.01 }
    - { link_name: gripper_link, res: 0.01 }
    - { link_name: l_gripper_finger_link, res: 0.01 }
    - { link_name: r_gripper_finger_link, res: 0.01 }
    # # Links with interfering collision geometry (internal parts, head)
    # - { link_name: torso_fixed_link, res: 0.01 }
    # - { link_name: bellows_link, res: 0.01 }
    # - { link_name: bellows_link2, res: 0.01 }
    # - { link_name: head_pan_link, res: 0.01 }
    # - { link_name: head_tilt_link, res: 0.01 }
    # # Links qithout collision geometry (stated here for reference)
    # - link_name: laser_link
    # - link_name: head_camera_link
    # - link_name: head_camera_depth_frame
    # - link_name: head_camera_depth_optical_frame
    # - link_name: head_camera_rgb_frame
    # - link_name: head_camera_rgb_optical_frame
  spheres_models:
    - link_name: torso_lift_link
      # auto: true
      # radius: 0.02
      auto: false
      spheres:
        # * * * * *
        # *       *
        #   *****

        # level 1
        - { name: l0001, x: -0.020, y:  0.140, z:  0.060, radius: 0.010, priority: 5 }
        - { name: l0002, x: -0.020, y: -0.140, z:  0.060, radius: 0.010, priority: 5 }
        - { name: l0003, x: -0.020, y:  0.070, z:  0.060, radius: 0.010, priority: 5 }
        - { name: l0004, x: -0.020, y: -0.070, z:  0.060, radius: 0.010, priority: 5 }
        - { name: l0005, x: -0.020, y:  0.000, z:  0.060, radius: 0.010, priority: 5 }

        - { name: l0006, x: -0.070, y:  0.140, z:  0.060, radius: 0.010, priority: 5 }
        - { name: l0007, x: -0.070, y: -0.140, z:  0.060, radius: 0.010, priority: 5 }

        - { name: l0008, x: -0.120, y:  0.120, z:  0.060, radius: 0.010, priority: 5 }
        - { name: l0009, x: -0.120, y: -0.120, z:  0.060, radius: 0.010, priority: 5 }
        - { name: l0010, x: -0.120, y:  0.060, z:  0.060, radius: 0.010, priority: 5 }
        - { name: l0011, x: -0.120, y: -0.060, z:  0.060, radius: 0.010, priority: 5 }
        - { name: l0012, x: -0.120, y:  0.000, z:  0.060, radius: 0.010, priority: 5 }

        # level 2
        - { name: l0201, x: -0.020, y:  0.140, z:  0.120, radius: 0.010, priority: 5 }
        - { name: l0202, x: -0.020, y: -0.140, z:  0.120, radius: 0.010, priority: 5 }
        - { name: l0203, x: -0.020, y:  0.070, z:  0.120, radius: 0.010, priority: 5 }
        - { name: l0204, x: -0.020, y: -0.070, z:  0.120, radius: 0.010, priority: 5 }
        - { name: l0205, x: -0.020, y:  0.000, z:  0.120, radius: 0.010, priority: 5 }

        - { name: l0206, x: -0.070, y:  0.140, z:  0.120, radius: 0.010, priority: 5 }
        - { name: l0207, x: -0.070, y: -0.140, z:  0.120, radius: 0.010, priority: 5 }

        - { name: l0208, x: -0.120, y:  0.120, z:  0.120, radius: 0.010, priority: 5 }
        - { name: l0209, x: -0.120, y: -0.120, z:  0.120, radius: 0.010, priority: 5 }
        - { name: l0210, x: -0.120, y:  0.060, z:  0.120, radius: 0.010, priority: 5 }
        - { name: l0211, x: -0.120, y: -0.060, z:  0.120, radius: 0.010, priority: 5 }
        - { name: l0212, x: -0.120, y:  0.000, z:  0.120, radius: 0.010, priority: 5 }

        # level 3
        - { name: l0301, x: -0.020, y:  0.140, z:  0.180, radius: 0.010, priority: 5 }
        - { name: l0302, x: -0.020, y: -0.140, z:  0.180, radius: 0.010, priority: 5 }
        - { name: l0303, x: -0.020, y:  0.070, z:  0.180, radius: 0.010, priority: 5 }
        - { name: l0304, x: -0.020, y: -0.070, z:  0.180, radius: 0.010, priority: 5 }
        - { name: l0305, x: -0.020, y:  0.000, z:  0.180, radius: 0.010, priority: 5 }

        - { name: l0306, x: -0.070, y:  0.140, z:  0.180, radius: 0.010, priority: 5 }
        - { name: l0307, x: -0.070, y: -0.140, z:  0.180, radius: 0.010, priority: 5 }

        - { name: l0308, x: -0.120, y:  0.120, z:  0.180, radius: 0.010, priority: 5 }
        - { name: l0309, x: -0.120, y: -0.120, z:  0.180, radius: 0.010, priority: 5 }
        - { name: l0310, x: -0.120, y:  0.060, z:  0.180, radius: 0.010, priority: 5 }
        - { name: l0311, x: -0.120, y: -0.060, z:  0.180, radius: 0.010, priority: 5 }
        - { name: l0312, x: -0.120, y:  0.000, z:  0.180, radius: 0.010, priority: 5 }

        # level 4
        - { name: l0401, x: -0.020, y:  0.140, z:  0.240, radius: 0.010, priority: 5 }
        - { name: l0402, x: -0.020, y: -0.140, z:  0.240, radius: 0.010, priority: 5 }
        - { name: l0403, x: -0.020, y:  0.070, z:  0.240, radius: 0.010, priority: 5 }
        - { name: l0404, x: -0.020, y: -0.070, z:  0.240, radius: 0.010, priority: 5 }
        - { name: l0405, x: -0.020, y:  0.000, z:  0.240, radius: 0.010, priority: 5 }

        - { name: l0406, x: -0.070, y:  0.140, z:  0.240, radius: 0.010, priority: 5 }
        - { name: l0407, x: -0.070, y: -0.140, z:  0.240, radius: 0.010, priority: 5 }

        - { name: l0408, x: -0.120, y:  0.120, z:  0.240, radius: 0.010, priority: 5 }
        - { name: l0409, x: -0.120, y: -0.120, z:  0.240, radius: 0.010, priority: 5 }
        - { name: l0410, x: -0.120, y:  0.060, z:  0.240, radius: 0.010, priority: 5 }
        - { name: l0411, x: -0.120, y: -0.060, z:  0.240, radius: 0.010, priority: 5 }
        - { name: l0412, x: -0.120, y:  0.000, z:  0.240, radius: 0.010, priority: 5 }

        # level 5
        - { name: l0501, x: -0.020, y:  0.140, z:  0.300, radius: 0.010, priority: 5 }
        - { name: l0502, x: -0.020, y: -0.140, z:  0.300, radius: 0.010, priority: 5 }
        - { name: l0503, x: -0.020, y:  0.070, z:  0.300, radius: 0.010, priority: 5 }
        - { name: l0504, x: -0.020, y: -0.070, z:  0.300, radius: 0.010, priority: 5 }
        - { name: l0505, x: -0.020, y:  0.000, z:  0.300, radius: 0.010, priority: 5 }

        - { name: l0506, x: -0.070, y:  0.140, z:  0.300, radius: 0.010, priority: 5 }
        - { name: l0507, x: -0.070, y: -0.140, z:  0.300, radius: 0.010, priority: 5 }

        - { name: l0508, x: -0.120, y:  0.120, z:  0.300, radius: 0.010, priority: 5 }
        - { name: l0509, x: -0.120, y: -0.120, z:  0.300, radius: 0.010, priority: 5 }
        - { name: l0510, x: -0.120, y:  0.060, z:  0.300, radius: 0.010, priority: 5 }
        - { name: l0511, x: -0.120, y: -0.060, z:  0.300, radius: 0.010, priority: 5 }
        - { name: l0512, x: -0.120, y:  0.000, z:  0.300, radius: 0.010, priority: 5 }

        # level 6
        - { name: l0601, x: -0.020, y:  0.140, z:  0.360, radius: 0.010, priority: 5 }
        - { name: l0602, x: -0.020, y: -0.140, z:  0.360, radius: 0.010, priority: 5 }
        - { name: l0603, x: -0.020, y:  0.070, z:  0.360, radius: 0.010, priority: 5 }
        - { name: l0604, x: -0.020, y: -0.070, z:  0.360, radius: 0.010, priority: 5 }
        - { name: l0605, x: -0.020, y:  0.000, z:  0.360, radius: 0.010, priority: 5 }

        - { name: l0606, x: -0.070, y:  0.140, z:  0.360, radius: 0.010, priority: 5 }
        - { name: l0607, x: -0.070, y: -0.140, z:  0.360, radius: 0.010, priority: 5 }

        - { name: l0608, x: -0.120, y:  0.120, z:  0.360, radius: 0.010, priority: 5 }
        - { name: l0609, x: -0.120, y: -0.120, z:  0.360, radius: 0.010, priority: 5 }
        - { name: l0610, x: -0.120, y:  0.060, z:  0.360, radius: 0.010, priority: 5 }
        - { name: l0611, x: -0.120, y: -0.060, z:  0.360, radius: 0.010, priority: 5 }
        - { name: l0612, x: -0.120, y:  0.000, z:  0.360, radius: 0.010, priority: 5 }

        # level 7
        - { name: l0701, x: -0.020, y:  0.140, z:  0.420, radius: 0.010, priority: 5 }
        - { name: l0702, x: -0.020, y: -0.140, z:  0.420, radius: 0.010, priority: 5 }
        - { name: l0703, x: -0.020, y:  0.070, z:  0.420, radius: 0.010, priority: 5 }
        - { name: l0704, x: -0.020, y: -0.070, z:  0.420, radius: 0.010, priority: 5 }
        - { name: l0705, x: -0.020, y:  0.000, z:  0.420, radius: 0.010, priority: 5 }

        - { name: l0706, x: -0.070, y:  0.140, z:  0.420, radius: 0.010, priority: 5 }
        - { name: l0707, x: -0.070, y: -0.140, z:  0.420, radius: 0.010, priority: 5 }

        - { name: l0708, x: -0.120, y:  0.120, z:  0.420, radius: 0.010, priority: 5 }
        - { name: l0709, x: -0.120, y: -0.120, z:  0.420, radius: 0.010, priority: 5 }
        - { name: l0710, x: -0.120, y:  0.060, z:  0.420, radius: 0.010, priority: 5 }
        - { name: l0711, x: -0.120, y: -0.060, z:  0.420, radius: 0.010, priority: 5 }
        - { name: l0712, x: -0.120, y:  0.000, z:  0.420, radius: 0.010, priority: 5 }

        # level 8
        - { name: l0801, x: -0.020, y:  0.140, z:  0.460, radius: 0.010, priority: 5 }
        - { name: l0802, x: -0.020, y: -0.140, z:  0.460, radius: 0.010, priority: 5 }
        - { name: l0803, x: -0.020, y:  0.070, z:  0.460, radius: 0.010, priority: 5 }
        - { name: l0804, x: -0.020, y: -0.070, z:  0.460, radius: 0.010, priority: 5 }
        - { name: l0805, x: -0.020, y:  0.000, z:  0.460, radius: 0.010, priority: 5 }

        - { name: l0806, x: -0.070, y:  0.140, z:  0.460, radius: 0.010, priority: 5 }
        - { name: l0807, x: -0.070, y: -0.140, z:  0.460, radius: 0.010, priority: 5 }

        - { name: l0808, x: -0.120, y:  0.120, z:  0.460, radius: 0.010, priority: 5 }
        - { name: l0809, x: -0.120, y: -0.120, z:  0.460, radius: 0.010, priority: 5 }
        - { name: l0810, x: -0.120, y:  0.060, z:  0.460, radius: 0.010, priority: 5 }
        - { name: l0811, x: -0.120, y: -0.060, z:  0.460, radius: 0.010, priority: 5 }
        - { name: l0812, x: -0.120, y:  0.000, z:  0.460, radius: 0.010, priority: 5 }

        # level 9
        - { name: l0901, x: -0.020, y:  0.140, z:  0.540, radius: 0.010, priority: 5 }
        - { name: l0902, x: -0.020, y: -0.140, z:  0.540, radius: 0.010, priority: 5 }
        - { name: l0903, x: -0.020, y:  0.070, z:  0.540, radius: 0.010, priority: 5 }
        - { name: l0904, x: -0.020, y: -0.070, z:  0.540, radius: 0.010, priority: 5 }
        - { name: l0905, x: -0.020, y:  0.000, z:  0.540, radius: 0.010, priority: 5 }

        - { name: l0906, x: -0.070, y:  0.140, z:  0.540, radius: 0.010, priority: 5 }
        - { name: l0907, x: -0.070, y: -0.140, z:  0.540, radius: 0.010, priority: 5 }

        - { name: l0908, x: -0.120, y:  0.120, z:  0.540, radius: 0.010, priority: 5 }
        - { name: l0909, x: -0.120, y: -0.120, z:  0.540, radius: 0.010, priority: 5 }
        - { name: l0910, x: -0.120, y:  0.060, z:  0.540, radius: 0.010, priority: 5 }
        - { name: l0911, x: -0.120, y: -0.060, z:  0.540, radius: 0.010, priority: 5 }
        - { name: l0912, x: -0.120, y:  0.000, z:  0.540, radius: 0.010, priority: 5 }

        # level 10
        - { name: l1001, x: -0.020, y:  0.120, z:  0.600, radius: 0.010, priority: 5 }
        - { name: l1002, x: -0.020, y: -0.120, z:  0.600, radius: 0.010, priority: 5 }
        - { name: l1003, x: -0.020, y:  0.080, z:  0.600, radius: 0.010, priority: 5 }
        - { name: l1004, x: -0.020, y: -0.080, z:  0.600, radius: 0.010, priority: 5 }
        - { name: l1005, x: -0.020, y:  0.000, z:  0.600, radius: 0.010, priority: 5 }

        - { name: l1006, x: -0.060, y:  0.120, z:  0.600, radius: 0.010, priority: 5 }
        - { name: l1007, x: -0.060, y: -0.120, z:  0.600, radius: 0.010, priority: 5 }

        - { name: l1008, x: -0.100, y:  0.100, z:  0.600, radius: 0.010, priority: 5 }
        - { name: l1009, x: -0.100, y: -0.100, z:  0.600, radius: 0.010, priority: 5 }
        - { name: l1010, x: -0.100, y:  0.050, z:  0.600, radius: 0.010, priority: 5 }
        - { name: l1011, x: -0.100, y: -0.050, z:  0.600, radius: 0.010, priority: 5 }
        - { name: l1012, x: -0.100, y:  0.000, z:  0.600, radius: 0.010, priority: 5 }

        # head
        # * * * *
        # * * * *
        # * * * *
        #  * * *
        - { name: l1101, x:  0.210, y:  0.110, z:  0.663, radius: 0.010, priority: 5 }
        - { name: l1102, x:  0.210, y: -0.110, z:  0.663, radius: 0.010, priority: 5 }
        - { name: l1103, x:  0.210, y:  0.035, z:  0.663, radius: 0.010, priority: 5 }
        - { name: l1104, x:  0.210, y: -0.035, z:  0.663, radius: 0.010, priority: 5 }

        - { name: l1105, x:  0.140, y:  0.110, z:  0.663, radius: 0.010, priority: 5 }
        - { name: l1106, x:  0.140, y: -0.110, z:  0.663, radius: 0.010, priority: 5 }
        - { name: l1107, x:  0.140, y:  0.035, z:  0.663, radius: 0.010, priority: 5 }
        - { name: l1108, x:  0.140, y: -0.035, z:  0.663, radius: 0.010, priority: 5 }

        - { name: l1109, x:  0.060, y:  0.110, z:  0.663, radius: 0.010, priority: 5 }
        - { name: l1110, x:  0.060, y: -0.110, z:  0.663, radius: 0.010, priority: 5 }
        - { name: l1111, x:  0.060, y:  0.035, z:  0.663, radius: 0.010, priority: 5 }
        - { name: l1112, x:  0.060, y: -0.035, z:  0.663, radius: 0.010, priority: 5 }

        - { name: l1113, x: -0.015, y:  0.060, z:  0.640, radius: 0.010, priority: 5 }
        - { name: l1114, x: -0.015, y: -0.060, z:  0.640, radius: 0.010, priority: 5 }
        - { name: l1115, x: -0.015, y:  0.000, z:  0.640, radius: 0.010, priority: 5 }

        # shoulder connection
        - { name: l1201, x:  0.120, y:  0.000, z:  0.200, radius: 0.010, priority: 5 }
    - link_name: shoulder_pan_link
      # auto: true
      # radius: 0.02
      auto: false
      spheres:
        - { name: l1301, x:  0.000, y: 0.0, z:  0.0, radius: 0.010, priority: 5 }
    - link_name: shoulder_lift_link
      # auto: true
      # radius: 0.02
      auto: false
      spheres:
        - { name: l1401, x:  0.000, y: -0.020, z:  0.0, radius: 0.010, priority: 5 }
        - { name: l1402, x:  0.000, y:  0.020, z:  0.0, radius: 0.010, priority: 5 }
        - { name: l1403, x:  0.103, y:  0.000, z:  0.0, radius: 0.010, priority: 5 }
    - link_name: upperarm_roll_link
      # auto: true
      # radius: 0.02
      auto: false
      spheres:
        - { name: l1501, x:  0.000, y:  0.000, z:  0.0, radius: 0.010, priority: 5 }
    - link_name: elbow_flex_link
      # auto: true
      # radius: 0.02
      auto: false
      spheres:
        - { name: l1601, x:  0.000, y: -0.020, z:  0.0, radius: 0.010, priority: 5 }
        - { name: l1602, x:  0.000, y:  0.020, z:  0.0, radius: 0.010, priority: 5 }
        - { name: l1603, x:  0.095, y:  0.000, z:  0.0, radius: 0.010, priority: 5 }
    - link_name: forearm_roll_link
      # auto: true
      # radius: 0.02
      auto: false
      spheres:
        - { name: l1701, x:  0.000, y:  0.000, z:  0.0, radius: 0.010, priority: 5 }
    - link_name: wrist_flex_link
      # auto: true
      # radius: 0.02
      auto: false
      spheres:
        - { name: l1801, x:  0.000, y: -0.020, z:  0.0, radius: 0.010, priority: 5 }
        - { name: l1802, x:  0.000, y:  0.020, z:  0.0, radius: 0.010, priority: 5 }
        - { name: l1803, x:  0.037, y:  0.000, z:  0.0, radius: 0.010, priority: 5 }
    - link_name: wrist_roll_link
      # auto: true
      # radius: 0.02
      auto: false
      spheres:
        - { name: l1901, x:  0.000, y:  0.000, z:  0.0, radius: 0.010, priority: 5 }
    - link_name: gripper_link
      # auto: true
      # radius: 0.02
      auto: false
      spheres:
        # - { name: l2001, x: -0.070, y: -0.0, z:  0.0, radius: 0.010, priority: 5 }
        - { name: l2001, x: -0.070, y: -0.020, z:  0.0, radius: 0.010, priority: 5 }
        - { name: l2002, x: -0.070, y:  0.020, z:  0.0, radius: 0.010, priority: 5 }
    - link_name: l_gripper_finger_link
      # auto: true
      # radius: 0.02
      auto: false
      spheres:
        - { name: l2101, x:  0.000, y: -0.005, z:  0.005, radius: 0.010, priority: 5 }
        - { name: l2101, x:  0.025, y: -0.005, z:  0.005, radius: 0.010, priority: 5 }
    - link_name: r_gripper_finger_link
      # auto: true
      # radius: 0.02
      auto: false
      spheres:
        - { name: l2101, x:  0.000, y:  0.005, z:  0.005, radius: 0.010, priority: 5 }
        - { name: l2101, x:  0.025, y:  0.005, z:  0.005, radius: 0.010, priority: 5 }
  collision_groups:
    - name: arm_with_torso
      links:
        - name: torso_lift_link
        - name: shoulder_pan_link
        - name: shoulder_lift_link
        - name: upperarm_roll_link
        - name: elbow_flex_link
        - name: forearm_roll_link
        - name: wrist_flex_link
        - name: wrist_roll_link
        - name: gripper_link
        - name: l_gripper_finger_link
        - name: r_gripper_finger_link
